// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {schema} from '../models';

export function GetResourceParams(arg1:string):Promise<Array<string>>;

export function LocalSearch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<schema.LocalSearchResponse>;

export function Stardust(arg1:string):Promise<string>;
