// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetResourceParams(arg1) {
  return window['go']['app']['Search']['GetResourceParams'](arg1);
}

export function LocalSearch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Search']['LocalSearch'](arg1, arg2, arg3, arg4);
}

export function Stardust(arg1) {
  return window['go']['app']['Search']['Stardust'](arg1);
}
